# Generated by Django 4.2.4 on 2023-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JWTUser',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('password_hash', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
