# Generated by Django 4.2.4 on 2023-08-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_auth', '0002_baseuser_smalltoken_delete_jwtuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmallToken',
        ),
    ]
