# Generated by Django 4.2.4 on 2023-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_remove_address_create_date_remove_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='url',
            field=models.URLField(max_length=32779),
        ),
    ]
